[package]
name = "rc_borrow_mut"
authors = [ "Finn Bear" ]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/finnbear/rc_borrow_mut/"
description = "Mutably borrow the contents of an Rc."
